version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:14.15

jobs:
  Build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Run Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  Test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Test
          command: npm run test
  Publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  PublishModule:
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Authorization:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - Build
            - Test
      - Publish:
          requires:
            - Authorization
          filters:
            branches:
              only:
                - master